### ISSUE TITLE
StatusBar Visibility

### ISSUE THREAD

**Issue by o-aloqaily** [yosif111/FTCAPP#1]
StatusBar is not quite visible on iOS, look for a solution.

**Comment by BaselAlebdi** [comment]
Working on it!

**Comment by o-aloqaily** [comment]
Good luck, I have to mention I've tried doing the following

- changing it's color to white
didn't work because it's color becomes invisible on other tabs.

- placing a white background for it with absolute position
did not work because ReactNative does not provide fixed view on screen, so when scrolling the screen down this disappears.

**Comment by BaselAlebdi** [comment]
Done! Added marginTop in ImageView for IOS only.

**Comment by o-aloqaily** [comment]
Good job! can you do it for the login screen as well?
