### ISSUE TITLE
General Points Submission Is Not Working Properly (Android Specific)

### ISSUE THREAD

**Issue by o-aloqaily** [yosif111/FTCAPP#6]
When Opening General Points Submission Screen, "submit for who?" is not showing any users and user can't pick who to submit points for, issue was reported on android and it needs to be checked on iOS as well.

**Comment by yosif111** [comment]
i'm on it friend, why worry?

**Comment by o-aloqaily** [comment]
انا موجود انتا ليش خوف؟

**Comment by yosif111** [comment]
Done 👍
